version: 0.2

phases:
  install:
    commands:
      - echo "Starting build process..."
  build:
    commands:
      - echo "Build step (no zip needed for Lambda here)..."

artifacts:
  files:
    - index.js
    - package.json
    - node_modules/**/*
  discard-paths: yes

